services:
  # Frontend Static Site
  - type: static_site
    name: plant-pantry-frontend
    repo: https://github.com/JaceG/Plant-Pantry
    branch: main
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Web Service
  - type: web
    name: Plant-Pantry
    repo: https://github.com/JaceG/Plant-Pantry
    branch: main
    rootDir: server
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
